#include "ui_internal.h"
#include "document.h"
#include <yyjson.h>
#include <stdlib.h>
#include <string.h>
typedef struct{char *id,*label,*value;char **options;size_t count;} FormField;
struct TomForm{TomWindow *window;TomFont font;TomDocument *document;TomEditor *editor;FormField *fields;size_t count;int active,first,x,y,width,height,focused,scroll_dragging,scroll_grab;};
static char *duplicate(const char *s){if(!s)return NULL;char *p=malloc(strlen(s)+1);if(p)strcpy(p,s);return p;}
static int32_t valid(TomForm *f){return f&&tom_ui_on_main()&&!f->window->closed?TOM_OK:TOM_RESOURCE;}
static void fields_free(FormField *fields,size_t n){for(size_t i=0;i<n;i++){free(fields[i].id);free(fields[i].label);free(fields[i].value);for(size_t k=0;k<fields[i].count;k++)free(fields[i].options[k]);free(fields[i].options);}free(fields);}
static int rows(TomForm *f){int n=f->height/78;return n>0?n:1;}
static int max_first(TomForm *f){int max=(int)f->count-rows(f);return max>0?max:0;}
static int content_width(TomForm *f){return f->width-24;}
static int32_t flush(TomForm *f){if(f->active<0||f->fields[f->active].count)return TOM_OK;char *value=duplicate(f->document->state.text->data);if(!value)return TOM_MEMORY;free(f->fields[f->active].value);f->fields[f->active].value=value;return TOM_OK;}
static int32_t position_editor(TomForm *f){if(f->active<0)return TOM_OK;if(f->active<f->first||f->active>=f->first+rows(f))return tom_editor_focus(f->editor,0);return tom_editor_area(f->editor,f->x,f->y+(f->active-f->first)*78+24,content_width(f),46);}
static int32_t place(TomForm *f){if(f->active<0)return TOM_OK;if(f->active<f->first)f->first=f->active;if(f->active>=f->first+rows(f))f->first=f->active-rows(f)+1;return position_editor(f);}
static int32_t set_first(TomForm *f,int first){if(first<0)first=0;if(first>max_first(f))first=max_first(f);if(first==f->first)return TOM_OK;int32_t e=flush(f);if(e)return e;f->first=first;e=position_editor(f);if(!e&&f->active>=f->first&&f->active<f->first+rows(f)&&f->focused&&!f->fields[f->active].count)e=tom_editor_focus(f->editor,1);return e;}
static float thumb_height(TomForm *f){float track=(float)f->height-4;float thumb=track*rows(f)/(float)f->count;if(thumb<28)thumb=28;return thumb>track?track:thumb;}
static float thumb_y(TomForm *f){return (float)f->y+2+((float)f->height-4-thumb_height(f))*f->first/max_first(f);}
static int32_t scroll_from_mouse(TomForm *f,int y){float travel=(float)f->height-4-thumb_height(f);int first=travel>0?(int)(((float)y-f->y-2-f->scroll_grab)*max_first(f)/travel+.5f):0;return set_first(f,first);}
static int32_t activate(TomForm *f,int index){if(index<0||index>=(int)f->count)return TOM_BOUNDS;int32_t e=flush(f);if(e)return e;TomDocument *d=NULL;TomText *json=NULL;e=tom_document_new(f->fields[index].value,16777216,33554432,&d);if(!e)e=tom_text_dynamic_new("",67108864,&json);if(!e)e=tom_document_serialize(d,json);if(!e)e=tom_document_load(f->document,json->data);if(!e){f->active=index;e=place(f);}if(!e)e=tom_editor_focus(f->editor,f->focused&&!f->fields[index].count);tom_document_free(d);tom_text_free(json);return e;}
void tom_form_free(TomForm *f){if(!f)return;fields_free(f->fields,f->count);tom_editor_free(f->editor);tom_document_free(f->document);TTF_CloseFont(f->font.font);tom_ui_window_release(f->window);free(f);tom_object_released();}
int32_t tom_form_new(TomWindow *window,TomFont *font,TomForm **out){
 if(!window||!font||!out||window->closed||!tom_ui_on_main())return TOM_RESOURCE;TomForm *f=calloc(1,sizeof(*f));if(!f)return TOM_MEMORY;f->active=-1;f->width=500;f->height=500;f->window=window;f->font.font=TTF_CopyFont(font->font);int32_t e=f->font.font?tom_document_new("",16777216,33554432,&f->document):TOM_MEMORY;if(!e)e=tom_editor_new(window,f->document,&f->font,&f->editor);if(e){TTF_CloseFont(f->font.font);tom_document_free(f->document);free(f);return e;}tom_ui_window_retain(window);tom_object_acquired();tom_form_free(*out);*out=f;return TOM_OK;
}
int32_t tom_form_load(TomForm *f,const char *json){int32_t e=valid(f);if(e)return e;if(!tom_utf8_valid(json)||strlen(json)>16777216)return TOM_INVALID;
 yyjson_doc *doc=yyjson_read(json,strlen(json),0);yyjson_val *root=doc?yyjson_doc_get_root(doc):NULL;size_t n=yyjson_arr_size(root);if(!yyjson_is_arr(root)||n>128){yyjson_doc_free(doc);return TOM_INVALID;}FormField *fields=calloc(n?n:1,sizeof(*fields));if(!fields){yyjson_doc_free(doc);return TOM_MEMORY;}
 for(size_t i=0;!e&&i<n;i++){yyjson_val *v=yyjson_arr_get(root,i);const char *id=yyjson_get_str(yyjson_obj_get(v,"id")),*label=yyjson_get_str(yyjson_obj_get(v,"rotulo")),*value=yyjson_get_str(yyjson_obj_get(v,"valor"));if(!id||!*id||!label||!value){e=TOM_INVALID;break;}fields[i].id=duplicate(id);fields[i].label=duplicate(label);fields[i].value=duplicate(value);if(!fields[i].id||!fields[i].label||!fields[i].value){e=TOM_MEMORY;break;}for(size_t k=0;k<i;k++)if(!strcmp(fields[k].id,id))e=TOM_INVALID;
  yyjson_val *options=yyjson_obj_get(v,"opcoes");size_t count=yyjson_arr_size(options);if(count>256){e=TOM_CAPACITY;break;}if(count){fields[i].options=calloc(count,sizeof(char*));if(!fields[i].options){e=TOM_MEMORY;break;}fields[i].count=count;for(size_t k=0;k<count;k++){const char *option=yyjson_get_str(yyjson_arr_get(options,k));if(!option){e=TOM_INVALID;break;}fields[i].options[k]=duplicate(option);if(!fields[i].options[k]){e=TOM_MEMORY;break;}}}
 }
 if(!e){tom_editor_focus(f->editor,0);fields_free(f->fields,f->count);f->fields=fields;f->count=n;fields=NULL;f->active=-1;f->first=0;f->scroll_dragging=0;if(n)e=activate(f,0);}fields_free(fields,fields?n:0);yyjson_doc_free(doc);return e;
}
int32_t tom_form_area(TomForm *f,int32_t x,int32_t y,int32_t width,int32_t height){int32_t e=valid(f);if(e)return e;if(x<0||y<0||width<64||height<78||x+width>16384||y+height>16384)return TOM_BOUNDS;f->x=x;f->y=y;f->width=width;f->height=height;if(f->first>max_first(f))f->first=max_first(f);return position_editor(f);}
int32_t tom_form_focus(TomForm *f,int32_t focus){int32_t e=valid(f);if(e)return e;f->focused=focus!=0;if(!f->focused)f->scroll_dragging=0;return tom_editor_focus(f->editor,f->focused&&f->active>=f->first&&f->active<f->first+rows(f)&&!f->fields[f->active].count);}
static int32_t cycle(TomForm *f,int direction){FormField *field=&f->fields[f->active];size_t at=0;while(at<field->count&&strcmp(field->value,field->options[at]))at++;int index=(int)at+direction;if(index<0)index=(int)field->count-1;if(index>=(int)field->count)index=0;char *value=duplicate(field->options[index]);if(!value)return TOM_MEMORY;free(field->value);field->value=value;return TOM_OK;}
int32_t tom_form_event(TomForm *f,TomEvent *event,int32_t *consumed){int32_t e=valid(f);if(e)return e;if(!event||!consumed)return TOM_INVALID;*consumed=0;if(!f->focused||!f->count)return TOM_OK;
 if(event->kind==8){f->scroll_dragging=0;return TOM_OK;}
 if(event->kind==10&&f->scroll_dragging){*consumed=1;return scroll_from_mouse(f,event->y);}
 if(event->kind==11&&f->scroll_dragging){f->scroll_dragging=0;*consumed=1;return TOM_OK;}
 if(event->kind==4&&event->button==1&&max_first(f)>0&&event->x>=f->x+f->width-20&&event->x<f->x+f->width&&event->y>=f->y&&event->y<f->y+f->height){float top=thumb_y(f),thumb=thumb_height(f);f->scroll_grab=event->y>=top&&event->y<top+thumb?event->y-(int)top:(int)(thumb/2);f->scroll_dragging=1;*consumed=1;return scroll_from_mouse(f,event->y);}
 if(event->kind==4&&event->button==1&&event->x>=f->x&&event->x<f->x+content_width(f)&&event->y>=f->y&&event->y<f->y+rows(f)*78){int index=f->first+(event->y-f->y)/78;if(index<(int)f->count){e=activate(f,index);*consumed=1;if(!e&&f->fields[index].count)e=cycle(f,1);else if(!e)e=tom_editor_event(f->editor,event,consumed);}return e;}
 if(event->kind==12){int next=f->active+(event->wheel_y<0?1:-1);if(next<0)next=0;if(next>=(int)f->count)next=(int)f->count-1;*consumed=1;return activate(f,next);}
 if(event->kind==3&&(event->key==SDLK_TAB||(event->key==SDLK_RETURN&&!(event->modifiers&SDL_KMOD_SHIFT)))){int direction=event->modifiers&SDL_KMOD_SHIFT?-1:1;int next=(f->active+direction+(int)f->count)%(int)f->count;*consumed=1;return activate(f,next);}
 if(f->active<f->first||f->active>=f->first+rows(f))return TOM_OK;
 if(f->active>=0&&f->fields[f->active].count){if(event->kind==3&&(event->key==SDLK_LEFT||event->key==SDLK_RIGHT||event->key==SDLK_SPACE)){*consumed=1;return cycle(f,event->key==SDLK_LEFT?-1:1);}if(event->kind==2)*consumed=1;return TOM_OK;}
 return tom_editor_event(f->editor,event,consumed);
}
int32_t tom_form_draw(TomForm *f,int64_t now){int32_t e=valid(f);if(e)return e;e=tom_editor_tick(f->editor,now);for(int row=0;!e&&row<rows(f)&&f->first+row<(int)f->count;row++){int index=f->first+row,y=f->y+row*78;FormField *field=&f->fields[index];e=tom_draw_text(f->window,&f->font,field->label,f->x,y,0x38485cff);if(e)break;
 if(index==f->active&&!field->count)e=tom_editor_draw(f->editor);else{e=tom_draw_rect(f->window,f->x,y+24,content_width(f),46,index==f->active?0xe9f1fcff:0xf6f7f9ff);if(!e){SDL_Rect previous,clip={f->x+8,y+26,content_width(f)-16,42};bool clipped=SDL_RenderClipEnabled(f->window->renderer);SDL_GetRenderClipRect(f->window->renderer,&previous);SDL_SetRenderClipRect(f->window->renderer,&clip);e=tom_draw_text(f->window,&f->font,*field->value?field->value:field->count?"—":"",f->x+10,y+36,0x172638ff);SDL_SetRenderClipRect(f->window->renderer,clipped?&previous:NULL);}}}if(!e&&max_first(f)>0){e=tom_draw_rect(f->window,f->x+f->width-20,f->y+2,18,f->height-4,0xe7ebf0ff);if(!e)e=tom_draw_rect(f->window,f->x+f->width-18,(int)thumb_y(f),14,(int)thumb_height(f),f->scroll_dragging?0x43689cff:0x79879bff);}return e;}
int32_t tom_form_value(TomForm *f,const char *id,TomText *out){int32_t e=valid(f);if(e)return e;e=flush(f);if(e)return e;for(size_t i=0;i<f->count;i++)if(!strcmp(f->fields[i].id,id))return tom_text_set(out,f->fields[i].value);return TOM_BOUNDS;}
int32_t tom_form_data(TomForm *f,TomText *out){int32_t e=valid(f);if(e)return e;e=flush(f);if(e)return e;yyjson_mut_doc *doc=yyjson_mut_doc_new(NULL);yyjson_mut_val *root=doc?yyjson_mut_obj(doc):NULL;if(!root){yyjson_mut_doc_free(doc);return TOM_MEMORY;}yyjson_mut_doc_set_root(doc,root);for(size_t i=0;i<f->count;i++)if(!yyjson_mut_obj_add_strcpy(doc,root,f->fields[i].id,f->fields[i].value))e=TOM_MEMORY;char *json=!e?yyjson_mut_write(doc,0,NULL):NULL;if(!json)e=TOM_MEMORY;if(!e)e=tom_text_set(out,json);free(json);yyjson_mut_doc_free(doc);return e;}

int32_t tom_form_set(TomForm *f,const char *id,const char *value){int32_t e=valid(f);if(e)return e;if(!tom_utf8_valid(id)||!tom_utf8_valid(value))return TOM_INVALID;e=flush(f);if(e)return e;for(size_t i=0;i<f->count;i++)if(!strcmp(f->fields[i].id,id)){char *text=duplicate(value);if(!text)return TOM_MEMORY;free(f->fields[i].value);f->fields[i].value=text;if(f->active==(int)i){f->active=-1;return activate(f,(int)i);}return TOM_OK;}return TOM_BOUNDS;}
